### ISSUE TITLE
Thijssen book

### ISSUE THREAD

**Issue by aromanro** [CompPhysics/ComputationalPhysics2#7]
Hi,

I was browsing the repository and I found Thijssen's book in doc/literature. I'm not really sure if it's ok to put it public like that (there might be some copyright issues), maybe you left it there by mistake?

By the way, it's an awesome book, I started many of my open source projects based on that book, although some went further than that.

**Comment by mhjensen** [comment]
Thx so much for this Adrian,
I placed it there long time ago ‘cause it was impossible to get it anymore from the publisher. There was a chapter on Hartree-Fock we found useful.
And the copy the university library had was no longer available.
I don’t use it anymore actually so I just removed. But as you say it is  a good text. Thx for
pointing this out to me.
Best wishes,
Morten 
Morten Hjorth-Jensen, Michigan State University, USA and University of Oslo, Norway, http://mhjgit.github.io/info/doc/web/
